### ISSUE TITLE
Want to know about the work flow.

### ISSUE THREAD

**Issue by dineshadepu** [ybyygu/vecfx#1]
Hi,

Just curious about your workflow. In every file I see a comment on each function, some thing like 

```// [[file:~/Workspace/Programming/rust-libs/vecfx/math.org::*for%20Vec<f64>][for Vec<f64>:1]]```

I want to know, how you would generally write a library, or your workflow. Do you wirte todo is org mode and then implement them one by one.

Can you elaborate it?

**Comment by ybyygu** [comment]
Actually these codes are tangled from notes I wrote in org-mode. The work flow is called literate programming.

Reference:
- https://orgmode.org/worg/org-contrib/babel/intro.html

My emacs configurations:
- https://github.com/ybyygu/emacs (in chinese, based on spacemacs)

**Comment by dineshadepu** [comment]
Thanks for the resource. Can you give me some sample file of this or other repos, like octree? I want use this, that would be help me to start quick.

**Comment by ybyygu** [comment]
here it is my original org notes on octree algorithm in chinese:

https://github.com/ybyygu/rust-octree/tree/master/docs

https://github.com/ybyygu/rust-octree/commit/5bb5ef05ec2d6c1e05b431386ea1bd8b515c5096

sorry, I have no time to translate it in English.

Hope it helps!

**Comment by dineshadepu** [comment]
Hey, thanks for the file. Sorry If I am bothering. 

In the first two lines of the file has these lines 
```
#+SETUPFILE: ~/Notes/common.org
#+SETUPFILE: ~/Notes/coding.org
```
Can you upload them too?

Thank you.

**Comment by ybyygu** [comment]
[ybyygu@ARCHTower] ~/Notes 14:15:21
> cat coding.org 
#+STARTUP: indent

[ybyygu@ARCHTower] ~/Notes 14:15:23
> cat common.org 
#+AUTHOR: Wenping Guo
#+DATE: {{{modification-time(%Y-%m-%d, vc)}}}
#+EMAIL: ybyygu@gmail.com
#+OPTIONS:   H:2 num:t \n:nil @:t ::t |:t ^:{} -:t f:t *:t <:t tags:nil
#+OPTIONS:   TeX:dvipng skip:nil d:nil todo:t pri:nil
#+LINK: doi http://dx.doi.org/%s
#+LINK: google http://www.google.com/search?q=%s
#+STARTUP: overview hidestars indent
#+TAGS: [ Category : Starred(m) Scratch(c) Computer(o) Incoming(i) ]
#+TAGS: [ Work : Project(p) Action(a) ASAP(A) ]
#+TAGS: { Research : Idea(I) Summary(s) Question(q) Data(d) Paper(P) Code(C) }
#+TAGS: [ Paper : Review Theory Expt Zeolite ]
#+TAGS: [ Resource : Software Book Website Info ]
#+TAGS: [ Website : Forum ]
#+TAGS: { Context : @Home @Work @Mail }
#+EXCLUDE_TAGS: Scratch
#+TODO: TODO | DONE(@)
#+TODO: READ | DONE(d@)

**Comment by ybyygu** [comment]
A side note:

files tangling is slow in org-mode. To speed up, I tangle only the file at point using this function:

;; tangle blocks for current file at point
;; http://stackoverflow.com/questions/28727190/org-babel-tangle-only-one-code-block
;; call org-babel-tangle with C-u C-u
(defun gwp/org-babel-tangle-blocks()
  (interactive)
  (let ((current-prefix-arg '(16)))
    (call-interactively 'org-babel-tangle)
    )
  )


snippet taken from https://github.com/ybyygu/emacs/blob/2858e1846b28e1b81d23355650622b4a886db4e9/pkg/.spacemacs.d/init-org.el#L439
